"""empty message

Revision ID: 447ca7e66a6e
Revises: 
Create Date: 2020-11-18 23:25:19.448783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447ca7e66a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('celular', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('tipo_de_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
