"""empty message

Revision ID: 6caabfc86cdc
Revises: 447ca7e66a6e
Create Date: 2020-11-20 23:10:30.263492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6caabfc86cdc'
down_revision = '447ca7e66a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('celular', sa.String(length=11), nullable=False),
    sa.Column('tipo_de_user', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('regadm', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('banca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banca_id'], ['bancas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    op.drop_table('bancas')
    op.drop_table('users')
    # ### end Alembic commands ###
