"""empty message

Revision ID: a1dfd6b5aeeb
Revises: 447ca7e66a6e
Create Date: 2020-11-22 14:27:55.640507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1dfd6b5aeeb'
down_revision = '447ca7e66a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
